### ISSUE TITLE
Is header needed

### ISSUE THREAD

**Issue by remicollet** [weltling/parle#3]
In config.m4

      PHP_INSTALL_HEADERS([ext/parle/php_parle.h])

But this header don't expose any public API for other extensions.
Is this planed ? else this installation can probably be removed.

P.S. for downstream this mean that an additional "devel" package is needed

**Comment by weltling** [comment]
I've just commented the header installation out. In general, some API could be exposed later, right now i'm not sure which parts could be useful. Maybe some class entry declarations, but actually not sure otherwise. And according to the current guidelines https://wiki.php.net/internals/review_comments#php_extnameh_should_be_minimal there should be an extra header for that anyway. Solved for now.

Thanks.
