### ISSUE TITLE
What about adding a configureoption to package.xml to control enable utf-32?

### ISSUE THREAD

**Issue by mlocati** [weltling/parle#31]
That way, it'd be easier to set `--enable-parle-utf32` when installing via pecl/pickle...

**Comment by BenHanson** [comment]
@weltling Is this as easy as it looks?

**Comment by weltling** [comment]
Yeah, i guess it's https://pear.php.net/manual/en/guide.developers.package2.pecl.php we're talking about. @mlocati please feel free to file a PR if you're still interested. I'm a bit unsure here as per the doc, it'll be always interactive. Would otherwise need to check if it can go an unattended way, too.

Thanks
